### ISSUE TITLE
doesn't support default parameter values

### ISSUE THREAD

**Issue by Ganonside** [AMalininHere/language-javascript-better#10]
the syntax highlighter doesn't highlight methods that set default parameter values:
```js
myfunc(arg1, arg2 = 'foo') { ... }
```

**Comment by AMalininHere** [comment]
Ready to use. Thanks

**Comment by AMalininHere** [comment]
Methods now highlighted. But not a strings

**Comment by Ganonside** [comment]
i'm trying to get the strings working. i'll submit a PR if i do

**Comment by AMalininHere** [comment]
It would be a great.
